---
- name: Transfer and execute a script.
  hosts: servers
  remote_user: root
  tasks:
     - name: Transfer the script
       copy: src=deploy.sh dest=/app/ mode=0777

     - name: Execute the script
       command: sh /app/deploy.sh