---
- name: Transfer and execute a script.
  hosts: 172.31.6.246
  remote_user: root
  tasks:
     - name: Transfer the script
       copy: src=/var/lib/jenkins/workspace/capstoneProject_master/deploy.sh /var/lib/jenkins/workspace/capstoneProject_master/load-balancer.yaml dest=/app/ mode=0777

     - name: Execute the script
       command: sh /app/deploy.sh