---
- name: Transfer and execute a script.
  hosts: 172.31.6.246
  remote_user: root
  tasks:
     - name: Transfer the script
       copy: src=/var/lib/jenkins/workspace/capstoneProject_master/{{ item }} dest=/app/ mode=0777
       with_items:
         - deploy.sh
         - load-balancer.yaml
         - nginx.conf
       #copy: src=/var/lib/jenkins/workspace/capstoneProject_master/load-balancer.yaml dest=/app/ mode=0755

     - name: Execute the script
       command: sh /app/deploy.sh