apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer
  name: udacitycapstoneproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer
    spec:
      containers:
      - image: bonduu01/udacitycaptoneproject:latest
        name: udacitycapstoneproject
        ports:
        - containerPort: 8080